
#ifndef FIBONACHY_NIM_VECTOR_ALGEBRAIC_ADDENDUM_H
#define FIBONACHY_NIM_VECTOR_ALGEBRAIC_ADDENDUM_H

#include "vector_algebraic_addendum_def.h"

MAKE_VECTOR_ALGEBRAIC_ADDENDUM(Int);

MAKE_VECTOR_ALGEBRAIC_ADDENDUM(Double)

MAKE_VECTOR_ALGEBRAIC_ADDENDUM(GeneralType)

#endif //FIBONACHY_NIM_VECTOR_ALGEBRAIC_ADDENDUM_H
