#ifndef EXACT_COVER_VECTOR_H
#define EXACT_COVER_VECTOR_H

#include "vector_def.h"






MAKE_VECTOR(Int, SIMPLE, SIMPLE);
MAKE_VECTOR(Char, SIMPLE, SIMPLE);
MAKE_VECTOR(Double, SIMPLE, SIMPLE);
MAKE_VECTOR(Bool, SIMPLE, SIMPLE);
MAKE_VECTOR(Complex, SIMPLE, SIMPLE)


MAKE_VECTOR(VectorInt, STRUCT, STRUCT);

MAKE_VECTOR(VectorVectorInt, STRUCT, STRUCT);

MAKE_VECTOR(VectorBool, STRUCT, STRUCT)

MAKE_VECTOR(GeneralType, STRUCT, STRUCT)

MAKE_VECTOR(VectorGeneralType, STRUCT, STRUCT)



#endif //EXACT_COVER_VECTOR_H
